/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module sumador_1_bbit (
  input A,
  input B,
  input Cin,
  output Y,
  output Cout
);
  wire s0;
  assign s0 = (A ^ B);
  assign Y = (s0 ^ Cin);
  assign Cout = ((s0 & Cin) | (A & B));
endmodule
