/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Sumador4bits (
  input A,
  input B,
  input Cin,
  input C,
  input D,
  input E,
  input F,
  input G,
  input H,
  output W,
  output X,
  output Y,
  output Z,
  output Cout
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  assign s0 = (A ^ B);
  assign s2 = (C ^ D);
  assign s4 = (E ^ F);
  assign s6 = (G ^ H);
  assign W = (s0 ^ Cin);
  assign s1 = ((s0 & Cin) | (A & B));
  assign X = (s2 ^ s1);
  assign s3 = ((s2 & s1) | (C & D));
  assign Y = (s4 ^ s3);
  assign s5 = ((s4 & s3) | (E & F));
  assign Z = (s6 ^ s5);
  assign Cout = ((s6 & s5) | (G & H));
endmodule
